name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*"
      - "zephyr/*"
      - "**/*.h"
      - "**/*.dtsi"
      - "build.yaml"
      - ".github/workflows/build.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
